<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use DateTime;

class MapSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('maps')->insert([
            [
            'location_id'=> 1,
            'store_name'=>'田舎館駅',
            'adress' =>'〒038-1111 青森県南津軽郡田舎館村高樋宮本',
            'gormet'=> null,
            'key_word'=>'ABCが作った？',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 1,
            'store_name'=>'かねちゃん',
            'adress' =>'〒038-1113 青森県南津軽郡田舎館村田舎舘中辻１３３−７',
            'gormet'=> 'どんこラーメン',
            'key_word'=>'田んぼアートがすごい',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 1,
            'store_name'=>'創作料理　御幸',
            'adress' =>'〒036-0377 青森県黒石市中町３６',
            'gormet'=> 'つゆやきそば',
            'key_word'=> null,
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 1,
            'store_name'=>'青森県田舎館村',
            'adress' =>'青森県田舎館村',
            'gormet'=> null,
            'key_word'=>'食わしすぎ',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 1,
            'store_name'=>'食処ふじた',
            'adress' =>'〒036-0357 青森県黒石市追子野木３丁目４７０−１',
            'gormet'=> '焼きそば',
            'key_word'=>'焼きそば番組か',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 1,
            'store_name'=>'鳥文食堂',
            'adress' =>'〒038-1133 青森県南津軽郡田舎館村大根子松森１６９−８',
            'gormet'=> '焼きそば',
            'key_word'=> null,
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 2,
            'store_name'=>'長崎県五島列島',
            'adress' =>'長崎県五島列島',
            'gormet'=> null,
            'key_word'=>'せいじの移動　せいじにギャラはやらん',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 2,
            'store_name'=>'平安食堂',
            'adress' =>'〒853-0015 長崎県五島市東浜町１丁目１０−１５',
            'gormet'=> null,
            'key_word'=>'長崎丸出しの食堂やで',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 2,
            'store_name'=>'一登',
            'adress' =>'〒853-0007 長崎県五島市福江町１２−１',
            'gormet'=> null,
            'key_word'=>'せいじに下品と言われたくない大悟',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 2,
            'store_name'=>'ビッグヒライパワーセンター店',
            'adress' =>'〒853-0041 長崎県五島市籠淵町２１６３', 
            'gormet'=> '五島うどん',
            'key_word'=>null,
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 2,
            'store_name'=>'鬼岳',
            'adress' => '〒853-0013長崎県五島市上大津町2873-1',
            'gormet'=> null,
            'key_word'=>'もうないで',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 2,
            'store_name'=>'奥浦海鮮直売所',
            'adress' =>'〒853-0053 長崎県五島市奥浦町２１５３',
            'gormet'=> 'クエのしゃぶしゃぶ　キビナゴの刺身',
            'key_word'=> null,
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 3,
            'store_name'=>'沖島漁業会館',
            'adress' =>'〒523-0801 滋賀県近江八幡市沖島町４３',
            'gormet'=> null,
            'key_word'=>'三輪車に乗り、うまく運転できない',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 3,
            'store_name'=>'汀の精',
            'adress' =>'〒523-0801 滋賀県近江八幡市沖島町３４６−２５',
            'gormet'=> null,
            'key_word'=>'かたせとおじいちゃんの会話が成立しない',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 3,
            'store_name'=>'沖島小学校',
            'adress' =>'〒523-0801 滋賀県近江八幡市沖島町３６０',
            'gormet'=> null,
            'key_word'=>'シンプルに薄しぃ',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 3,
            'store_name'=>'いっぷくどう',
            'adress' =>'〒523-0801 滋賀県近江八幡市沖島町２４３',
            'gormet'=> '豚汁',
            'key_word'=> null,
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 4,
            'store_name'=>'頴娃駅',
            'adress' =>'〒891-0701 鹿児島県南九州市頴娃町郡',
            'gormet'=> null,
            'key_word'=>'頴でえいと読み、娃は読まない',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 4,
            'store_name'=>'招福そば',
            'adress' =>'〒891-0702 鹿児島県南九州市頴娃町牧之内３９６５',
            'gormet'=> 'ざるそば',
            'key_word'=> null,
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 4,
            'store_name'=>'ばあば亭',
            'adress' =>'〒891-0702 鹿児島県南九州市頴娃町牧之内１４４０',
            'gormet'=> 'ランチ',
            'key_word'=>'暇ですることない人が自分の家食堂にしたんや',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 4,
            'store_name'=>'えい中央温泉センター',
            'adress' =>'〒891-0702 鹿児島県南九州市頴娃町牧之内２８９０',
            'gormet'=> null,
            'key_word'=>'せいじのブラジリアン',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 4,
            'store_name'=>'居酒屋　勇気凛々',
            'adress' =>'〒891-0701 鹿児島県南九州市頴娃町郡９２１３−４',
            'gormet'=> 'ビール',
            'key_word'=>'せいじの失言2　せいじの立ちション',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 5,
            'store_name'=>'大寅屋',
            'adress' =>'〒879-0628 大分県豊後高田市新町９９２', 
            'gormet'=> 'ちゃんぽん',
            'key_word'=>'具志堅のウソ1東京 具志堅の子供嫌い 具志堅のウソ2大阪',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 5,
            'store_name'=>'大分県豊後高田市昭和の町',
            'adress' =>'大分県豊後高田市昭和の町',
            'gormet'=> null,
            'key_word'=>'具志堅花むしりとる　7個例えよ　具志堅沖縄に染みる',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 5,
            'store_name'=>'cafe CACHE*CACHE',
            'adress' =>'〒879-0628 大分県豊後高田市大字新町８９９',
            'gormet'=> null,
            'key_word'=>'ガールズバーあります？',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 6,
            'store_name'=>'禄剛崎',
            'adress' =>'〒927-1441 石川県珠洲市禄剛崎',
            'gormet'=> null,
            'key_word'=>'うそくさいナダル1',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 6,
            'store_name'=>'いかなてて',
            'adress' =>'〒927-1441 石川県珠洲市狼煙町７０−１', 
            'gormet'=> '焼きあごだしわかめうどん',
            'key_word'=>'うそくさいお世辞 2度と会えないでしょう',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 6,
            'store_name'=>'石川県珠洲市狼煙町',
            'adress' =>'石川県珠洲市狼煙町',
            'gormet'=> null,
            'key_word'=>'ナダルの奇行と怖い顔 ナダルの失礼 大根食って、スイカの皮みたい うそくさいナダル２',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 6,
            'store_name'=>'つばき茶屋',
            'adress' =>'〒927-1446 石川県珠洲市折戸町１−３−１',
            'gormet'=> 'イカさま定食',
            'key_word'=> null,
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 6,
            'store_name'=>'ゴジラ岩',
            'adress' =>'〒927-1304 石川県珠洲市馬緤町６',
            'gormet'=> null,
            'key_word'=>'ちっちゃいな',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 6,
            'store_name'=>'平家の里',
            'adress' =>'〒927-1322 石川県珠洲市長橋町13-17-2 珠洲製塩内', 
            'gormet'=> '一九二蕎麦',
            'key_word'=>'お父さんを悪人に仕立てるナダル',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 7,
            'store_name'=>'長野県高山村',
            'adress' =>'長野県高山村',
            'gormet'=> null,
            'key_word'=>'大吾の倒し方　アルファード１　アルファード２',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 7,
            'store_name'=>'子安そば　文の蔵',
            'adress' =>'〒382-0821 長野県上高井郡高山村牧１３３６',
            'gormet'=> '天ざる',
            'key_word'=>'フォローがない武井壮 全員馬鹿',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 7,
            'store_name'=>'ふじたや酒店',
            'adress' =>'〒382-0821 長野県上高井郡高山村牧１６５５−３',
            'gormet'=> 'ナッチョ',
            'key_word'=>'ロングコートの武井壮 カツアゲする武井壮',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 7,
            'store_name'=>'山田温泉大湯',
            'adress' =>'〒382-0816 長野県上高井郡高山村山田温泉３５８０',
            'gormet'=> null,
            'key_word'=>'モザイクが薄しぃ テレビ離れが加速する',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 7,
            'store_name'=>'食彩酒房　鼓',
            'adress' =>'〒382-0800 長野県上高井郡高山村高井３２２４−１１',
            'gormet'=> null,
            'key_word'=>'美女の前で脱ぐ武井壮',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 8,
            'store_name'=>'宝亭',
            'adress' =>'〒100-1511 東京都八丈島八丈町三根７６５',
            'gormet'=> null,
            'key_word'=>'おもろない',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 8,
            'store_name'=>'裏見ヶ滝温泉',
            'adress' =>'〒100-1623 東京都 八丈島八丈町中之郷１２４６',
            'gormet'=> null,
            'key_word'=>'ププッピドゥー',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 9,
            'store_name'=>'伊計ビーチ',
            'adress' =>'〒904-2421 沖縄県うるま市与那城伊計４０５', 
            'gormet'=> '沖縄そば',
            'key_word'=> null,
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 9,
            'store_name'=>'沖縄県うるま市浜比嘉島',
            'adress' =>'沖縄県うるま市浜比嘉島',
            'gormet'=> null,
            'key_word'=>'一発15万やから',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 9,
            'store_name'=>'エスパシオ',
            'adress' =>'〒904-2425 沖縄県うるま市与那城桃原１３５−１', 
            'gormet'=> 'アイスコーヒー',
            'key_word'=> null,
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 9,
            'store_name'=>'沖縄県うるま市宮城島',
            'adress' =>'沖縄県うるま市宮城島',
            'gormet'=> 'バナナ',
            'key_word'=>'相席たばこ　砂になりたい',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 10,
            'store_name'=>'さるふつ丸ごと館',
            'adress' =>'北海道宗谷郡猿払村 村浜鬼志別214', 
            'gormet'=> 'もりそば　かきあげ　アイスクリーム',
            'key_word'=>'そこはなに？　怖がられる長州　帰ってもいいですか？',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 10,
            'store_name'=>'北海道猿払村',
            'adress' =>'北海道猿払村',
            'gormet'=> 'ソフトほたて貝柱8粒　ビール',
            'key_word'=>'相席していーい？　食ってみな飛ぶぞ　凄いね　お前たち!　マジで飲んだぁ　バラァ',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 10,
            'store_name'=>'円丁牧場',
            'adress' =>'〒098-6225北海道猿払村（宗谷郡）宗谷郡猿払村芦野2162-14',
            'gormet'=> '牛乳',
            'key_word'=>'臭うな　牛の最後までのクソ　長州締めロング',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 11,
            'store_name'=>'三重県鳥羽市答志島',
            'adress' =>'三重県鳥羽市答志島',
            'gormet'=> null,
            'key_word'=>'連続殺人',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 11,
            'store_name'=>'まるみつ寿司',
            'adress' =>'〒517-0002 三重県鳥羽市答志町１１０６',
            'gormet'=> '上にぎり　めかぶの三杯酢　めかぶのみそ汁',
            'key_word'=>'独特の目薬の差し方　ノブはデブタレント　記憶なくしょーんか',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 12,
            'store_name'=>'御食事処　はましん',
            'adress' =>'〒701-3204 岡山県備前市日生町日生２４１−３０',
            'gormet'=> '穴子のひつまぶし',
            'key_word'=>'難しいボケ',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 12,
            'store_name'=>'とんかつ　かつ平',
            'adress' =>'〒701-3204 岡山県備前市日生町日生２４６−４０',
            'gormet'=> 'ヒレカツ定食',
            'key_word'=>'気まずい',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 12,
            'store_name'=>'CAFE RAD',
            'adress' =>'〒701-3204 岡山県備前市日生町日生６４１−４７',
            'gormet'=> 'ホットコーヒー　シフォンケーキ',
            'key_word'=>'しぽーん',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 12,
            'store_name'=>'きたろう',
            'adress' =>'〒701-3204 岡山県備前市日生町日生２４１−１７',
            'gormet'=> 'スープ焼きそば',
            'key_word'=>'のどちんこキュッキュ',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
            [
            'location_id'=> 12,
            'store_name'=>'たぬき山展望台',
            'adress' =>'〒701-3204 岡山県備前市日生町日生',
            'gormet'=> null,
            'key_word'=>'アーメマ',
            'created_at'=> new DateTime(),
            'updated_at'=> new DateTime(),
            'deleted_at'=> null,
            ],
        ]);
    }
}
